name: fluttet_hm10
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.31.15
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.4
  bluetooth_enable_fork: ^0.1.6
  very_good_analysis: ^5.1.0
  easy_localization: ^3.0.7
  shared_preferences: ^2.0.10
  geolocator: ^11.0.0
  provider:
  go_router: ^14.6.1
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  intl_utils: ^2.5.0
  change_app_package_name: ^1.4.0


flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
  remove_alpha_ios: true





flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/ac_images/
    - assets/ezgi/
    - assets/translations/en-US.json
    - assets/translations/tr-TR.json
    - assets/translations/de-DE.json
